os: osx
osx_image: xcode12.2
language: node_js
node_js: '12'
before_install:
  - npm install -g yarn
before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" -a "$BUILD_STAGE" = "" ]; then chmod +x scripts/add-osx-cert.sh;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" -a "$BUILD_STAGE" = "" ]; then ./scripts/add-osx-cert.sh;
    fi
script:
  - yarn test
